import {
  studentName,
  weekdayOrWeekend,
  fourItems,
  itemsWithLetter,
} from "../../js/script";

const animals = [
  "Aardvark",
  "Albatross",
  "Alligator",
  "Alpaca",
  "Ant",
  "Anteater",
  "Antelope",
  "Ape",
  "Armadillo",
  "Donkey",
  "Baboon",
  "Badger",
  "Barracuda",
  "Bat",
  "Bear",
  "Beaver",
  "Bee",
  "Bison",
  "Boar",
  "Buffalo",
  "Butterfly",
  "Camel",
  "Capybara",
  "Caribou",
  "Cassowary",
  "Cat",
  "Caterpillar",
  "Cattle",
  "Chamois",
  "Cheetah",
  "Chicken",
  "Chimpanzee",
  "Chinchilla",
  "Chough",
  "Clam",
  "Cobra",
  "Cockroach",
  "Cod",
  "Cormorant",
  "Coyote",
  "Crab",
  "Crane",
  "Crocodile",
  "Crow",
  "Curlew",
  "Deer",
  "Dinosaur",
  "Dog",
  "Dogfish",
  "Dolphin",
  "Dotterel",
  "Dove",
  "Dragonfly",
  "Duck",
  "Dugong",
  "Dunlin",
  "Eagle",
  "Echidna",
  "Eel",
  "Eland",
  "Elephant",
  "Elk",
  "Emu",
  "Falcon",
  "Ferret",
  "Finch",
  "Fish",
  "Flamingo",
  "Fly",
  "Fox",
  "Frog",
  "Gaur",
  "Gazelle",
  "Gerbil",
  "Giraffe",
  "Gnat",
  "Gnu",
  "Goat",
  "Goldfinch",
  "Goldfish",
  "Goose",
  "Gorilla",
  "Goshawk",
  "Grasshopper",
  "Grouse",
  "Guanaco",
  "Gull",
  "Hamster",
  "Hare",
  "Hawk",
  "Hedgehog",
  "Heron",
  "Herring",
  "Hippopotamus",
  "Hornet",
  "Horse",
  "Human",
  "Hummingbird",
  "Hyena",
  "Ibex",
  "Ibis",
  "Jackal",
  "Jaguar",
  "Jay",
  "Jellyfish",
  "Kangaroo",
  "Kingfisher",
  "Koala",
  "Kookabura",
  "Kouprey",
  "Kudu",
  "Lapwing",
  "Lark",
  "Lemur",
  "Leopard",
  "Lion",
  "Llama",
  "Lobster",
  "Locust",
  "Loris",
  "Louse",
  "Lyrebird",
  "Magpie",
  "Mallard",
  "Manatee",
  "Mandrill",
  "Mantis",
  "Marten",
  "Meerkat",
  "Mink",
  "Mole",
  "Mongoose",
  "Monkey",
  "Moose",
  "Mosquito",
  "Mouse",
  "Mule",
  "Narwhal",
  "Newt",
  "Nightingale",
  "Octopus",
  "Okapi",
  "Opossum",
  "Oryx",
  "Ostrich",
  "Otter",
  "Owl",
  "Oyster",
  "Panther",
  "Parrot",
  "Partridge",
  "Peafowl",
  "Pelican",
  "Penguin",
  "Pheasant",
  "Pig",
  "Pigeon",
  "Pony",
  "Porcupine",
  "Porpoise",
  "Quail",
  "Quelea",
  "Quetzal",
  "Rabbit",
  "Raccoon",
  "Rail",
  "Ram",
  "Rat",
  "Raven",
  "Red deer",
  "Red panda",
  "Reindeer",
  "Rhinoceros",
  "Rook",
  "Salamander",
  "Salmon",
  "Sand Dollar",
  "Sandpiper",
  "Sardine",
  "Scorpion",
  "Seahorse",
  "Seal",
  "Shark",
  "Sheep",
  "Shrew",
  "Skunk",
  "Snail",
  "Snake",
  "Sparrow",
  "Spider",
  "Spoonbill",
  "Squid",
  "Squirrel",
  "Starling",
  "Stingray",
  "Stinkbug",
  "Stork",
  "Swallow",
  "Swan",
  "Tapir",
  "Tarsier",
  "Termite",
  "Tiger",
  "Toad",
  "Trout",
  "Turkey",
  "Turtle",
  "Viper",
  "Vulture",
  "Wallaby",
  "Walrus",
  "Wasp",
  "Weasel",
  "Whale",
  "Wildcat",
  "Wolf",
  "Wolverine",
  "Wombat",
  "Woodcock",
  "Woodpecker",
  "Worm",
  "Wren",
  "Yak",
  "Zebra",
];

describe("function tests", () => {
  it("checks for weekend or weekday", () => {
    expect(weekdayOrWeekend("1995-12-17T03:24:00")).to.equal(
      "The date 1995-12-17 is a weekend"
    );
    expect(weekdayOrWeekend("1992-07-14T00:00:00")).to.equal(
      "The date 1992-07-14 is a weekday"
    );
    expect(weekdayOrWeekend("2022-08-24T00:00:00")).to.equal(
      "The date 2022-08-24 is a weekday"
    );
  });

  it("checks for first and last name", () => {
    expect(studentName({ firstName: "Cool", lastName: "Person" })).to.equal(
      "Student name is: Cool Person"
    );
    expect(studentName({ firstName: "Horsemaster", job: "General" })).to.equal(
      "Student name is: Horsemaster CLASSIFIED"
    );
    expect(studentName({ food: "Apple", lastName: "Stonewhistle" })).to.equal(
      "Student name is: CLASSIFIED Stonewhistle"
    );
    expect(studentName({ troy: "Abed", inThe: "Morning" })).to.equal(
      "No name available"
    );
  });

  it("joins words", () => {
    expect(fourItems(["Paul", "Ringo", "John", "George"])).to.equal(
      "Paul, Ringo, John and George"
    );
    expect(fourItems(["Hello", "there", "it's", "me"])).to.equal(
      "Hello, there, it's and me"
    );
    expect(fourItems(["Heads", "shoulders", "knees", "toes"])).to.equal(
      "Heads, shoulders, knees and toes"
    );
  });

  it("finds letters", () => {
    expect(itemsWithLetter(animals, "z")).to.deep.eq([
      "Chimpanzee",
      "Gazelle",
      "Quetzal",
      "Zebra",
    ]);
    expect(itemsWithLetter(animals, "b")).to.deep.eq([
      "Albatross",
      "Baboon",
      "Badger",
      "Barracuda",
      "Bat",
      "Bear",
      "Beaver",
      "Bee",
      "Bison",
      "Boar",
      "Buffalo",
      "Butterfly",
      "Capybara",
      "Caribou",
      "Cobra",
      "Crab",
      "Gerbil",
      "Hummingbird",
      "Ibex",
      "Ibis",
      "Kookabura",
      "Lobster",
      "Lyrebird",
      "Rabbit",
      "Spoonbill",
      "Stinkbug",
      "Wallaby",
      "Wombat",
      "Zebra",
    ]);
    expect(itemsWithLetter(animals, "Z")).to.deep.eq([
      "Chimpanzee",
      "Gazelle",
      "Quetzal",
      "Zebra",
    ]);
  });
});
